# Generated by Django 4.2.1 on 2023-07-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
